language: python
# python:
#   - "3.11-dev"


install:
  - pip install -r requirements.txt
  

script:
- black --check .
- flake8 --max-line-length=400 .
- coverage run manage.py test
- env


after_scripts:
- coveralls

- name: Coveralls GitHub Action
uses: coverallsapp/github-action@v2.3.3
            