language: python
# python:
#   - "3.11-dev"


install:
  - pip install -r requirements.txt
  

script:
- black --check .
- flake8 --max-line-length=400 .
- coverage run manage.py test
- coveralls
- env


# after_scripts:



deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ID
  secret_access_key: $AWS_KEY
    # secure: 
  region: us-west-2
  app: Django2
  env: Django2
  bucket_name: elasticbeanstalk-us-west-2-084375578870
  on:
    repo: ######
    branch: project
  skip_cleanup: 'true'

            