language: python
# python:
#   - "3.11-dev"


install:
  - pip install -r requirements.txt
  

script:
- black --check .
- flake8 --max-line-length=400 .
- coverage run manage.py test
- coveralls
- env


# after_scripts:



# deploy:
#   provider: elasticbeanstalk
#   access_key_id: ########
#   secret_access_key: ######
#     # secure: 
#   region: us-west-2
#   app: django-app
#   env: Django-app-env
#   bucket_name: elasticbeanstalk-us-west-2-992382724291
#   on:
#     repo: ######
#     branch: main
#   skip_cleanup: 'true'

            